#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Update system and install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Backup the original haproxy.cfg in case something goes wrong
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Clean the haproxy.cfg (optional step, if needed)
# sudo truncate -s 0 /etc/haproxy/haproxy.cfg

# Check if the configuration for frontend and backend exists
if ! grep -q "frontend tresorshingiro-frontend" /etc/haproxy/hap
